project_id = "lzfwyaofwpijmenqzehv"

[functions.football-api]
verify_jwt = false

[functions.sync-fixtures]
verify_jwt = false

[functions.save-prediction]
verify_jwt = false

[functions.update-live-fixtures]
verify_jwt = false
